<?xml version="1.0" encoding="UTF-8"?>
<ProjectTreeState projectID=".2jSluaGAqACtQDr" projectPath="C:\Users\Megafusto\Desktop\CivicSensWeb\documentazione\redmine\UML Sprint 4\Modelli.vpp">
	<TreeState name="ModelRepository" viewX="0" viewY="0"/>
	<TreeState name="DiagramNavigator" viewX="0" viewY="270">
		<ExpandedPath>DiagramNavigator</ExpandedPath>
		<ExpandedPath>DiagramNavigator,UML Diagrams</ExpandedPath>
		<ExpandedPath>ClassDiagram</ExpandedPath>
		<ExpandedPath>InteractionDiagram</ExpandedPath>
		<ExpandedPath>ComponentDiagram</ExpandedPath>
		<ExpandedPath>DeploymentDiagram</ExpandedPath>
		<SelectedPath>InteractionDiagram,6RewbZaGAqBwAScN</SelectedPath>
	</TreeState>
	<TreeState name="ClassBrowser" viewX="0" viewY="0"/>
	<TreeState name="LogicalView" viewX="0" viewY="0"/>
</ProjectTreeState>